// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_settings() {
  return window['go']['main']['App']['Get_settings']();
}

export function Greet(arg1, arg2) {
  return window['go']['main']['App']['Greet'](arg1, arg2);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
