// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get_settings():Promise<{[key: string]: string}>;

export function Greet(arg1:string,arg2:string):Promise<string>;

export function UpdateSetting(arg1:{[key: string]: string}):Promise<void>;
